In [ ]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.1
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.14.0
backcall                         0.2.0
beautifulsoup4                   4.11.2
bidict                           0.22.1
b

# Here We Use "keras" and "numpy"

In [ ]:
from keras import Sequential

In [ ]:
from keras.layers import Dense, SimpleRNN

In [ ]:
model = Sequential()

In [ ]:
model.add(SimpleRNN(4,input_shape=(4,5)))
model.add(Dense(1,activation="sigmoid"))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 4)                 40        
                                                                 
 dense_1 (Dense)             (None, 1)                 5         
                                                                 
Total params: 45 (180.00 Byte)
Trainable params: 45 (180.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.get_weights()

[array([[-0.14607453, -0.30302715, -0.7473103 ,  0.63715875],
        [ 0.4433359 , -0.5671515 ,  0.53475225, -0.46348223],
        [-0.81318784, -0.43396997,  0.16930234, -0.80486834],
        [ 0.10134315, -0.6843727 , -0.64842284, -0.5470474 ],
        [-0.3930389 ,  0.16265911, -0.52460873, -0.16147393]],
       dtype=float32),
 array([[ 0.5648824 ,  0.12349451,  0.29501006, -0.7606746 ],
        [ 0.16793218, -0.9838665 , -0.03699153, -0.04936803],
        [ 0.36864537,  0.00688425,  0.74039525,  0.56202155],
        [ 0.718893  ,  0.12926142, -0.6028397 ,  0.32104307]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.953046  ],
        [-0.41453117],
        [ 0.04592884],
        [ 0.5792484 ]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
model.get_weights()[0]

array([[-0.14607453, -0.30302715, -0.7473103 ,  0.63715875],
       [ 0.4433359 , -0.5671515 ,  0.53475225, -0.46348223],
       [-0.81318784, -0.43396997,  0.16930234, -0.80486834],
       [ 0.10134315, -0.6843727 , -0.64842284, -0.5470474 ],
       [-0.3930389 ,  0.16265911, -0.52460873, -0.16147393]],
      dtype=float32)

In [ ]:
model.get_weights()[0].shape

(5, 4)

In [ ]:
model.get_weights()[1]

array([[ 0.5648824 ,  0.12349451,  0.29501006, -0.7606746 ],
       [ 0.16793218, -0.9838665 , -0.03699153, -0.04936803],
       [ 0.36864537,  0.00688425,  0.74039525,  0.56202155],
       [ 0.718893  ,  0.12926142, -0.6028397 ,  0.32104307]],
      dtype=float32)

In [ ]:
model.get_weights()[1].shape

(4, 4)

In [ ]:
model.get_weights()[2]

array([0., 0., 0., 0.], dtype=float32)

In [ ]:
model.get_weights()[2].shape

(4,)

In [ ]:
from keras.datasets import imdb

In [ ]:
imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [ ]:
(X_train, y_train),(X_test,y_test) = imdb.load_data()

In [ ]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [ ]:
len(X_train[0])

218

In [ ]:
len(X_train[1])

189

In [ ]:
len(X_train[2])

141

In [ ]:
mylist=[]
for review in X_train:
  mylist.append(len(review))
min(mylist)

11

In [ ]:
X_train.shape

(25000,)

In [ ]:
X_test.shape

(25000,)

In [ ]:
import numpy as np
sent=[
    "india won the worldcup",
    "rohit played very well",
    "above all is my imagination",
    "bharat mata ki jay",
    "defenatly we gonna win next worldcup"
]

In [ ]:
sent

['india won the worldcup',
 'rohit played very well',
 'above all is my imagination',
 'bharat mata ki jay',
 'defenatly we gonna win next worldcup']

In [ ]:
from keras.preprocessing.text import Tokenizer # It is performing Integer Encoding

In [ ]:
tokenizer=Tokenizer()

In [ ]:
tokenizer.fit_on_texts(sent)

In [ ]:
tokenizer.word_index

{'worldcup': 1,
 'india': 2,
 'won': 3,
 'the': 4,
 'rohit': 5,
 'played': 6,
 'very': 7,
 'well': 8,
 'above': 9,
 'all': 10,
 'is': 11,
 'my': 12,
 'imagination': 13,
 'bharat': 14,
 'mata': 15,
 'ki': 16,
 'jay': 17,
 'defenatly': 18,
 'we': 19,
 'gonna': 20,
 'win': 21,
 'next': 22}

In [ ]:
tokenizer.word_counts

OrderedDict([('india', 1),
             ('won', 1),
             ('the', 1),
             ('worldcup', 2),
             ('rohit', 1),
             ('played', 1),
             ('very', 1),
             ('well', 1),
             ('above', 1),
             ('all', 1),
             ('is', 1),
             ('my', 1),
             ('imagination', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jay', 1),
             ('defenatly', 1),
             ('we', 1),
             ('gonna', 1),
             ('win', 1),
             ('next', 1)])

In [ ]:
tokenizer.document_count

5

In [ ]:
encoding = tokenizer.texts_to_sequences(sent)

In [ ]:
encoding

[[2, 3, 4, 1],
 [5, 6, 7, 8],
 [9, 10, 11, 12, 13],
 [14, 15, 16, 17],
 [18, 19, 20, 21, 22, 1]]

In [ ]:
from keras.utils import pad_sequences

In [ ]:
pad_sequences(encoding)

array([[ 0,  0,  2,  3,  4,  1],
       [ 0,  0,  5,  6,  7,  8],
       [ 0,  9, 10, 11, 12, 13],
       [ 0,  0, 14, 15, 16, 17],
       [18, 19, 20, 21, 22,  1]], dtype=int32)

In [ ]:
pad_sequences(encoding,padding="post")

array([[ 2,  3,  4,  1,  0,  0],
       [ 5,  6,  7,  8,  0,  0],
       [ 9, 10, 11, 12, 13,  0],
       [14, 15, 16, 17,  0,  0],
       [18, 19, 20, 21, 22,  1]], dtype=int32)

In [ ]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [ ]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [ ]:
X_train = pad_sequences(X_train,padding="post",maxlen=50)

In [ ]:
X_test = pad_sequences(X_test,padding="post",maxlen=50)

In [ ]:
model = Sequential()

In [ ]:
model.add(SimpleRNN(32,input_shape=(50,1)))

In [ ]:
model.add(Dense(1,activation="sigmoid"))

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_3 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5)

Epoch 1/5
782/782 [==============================] - 35s 42ms/step - loss: 0.6940 - accuracy: 0.5014 - val_loss: 0.6941 - val_accuracy: 0.5094
Epoch 2/5
782/782 [==============================] - 31s 39ms/step - loss: 0.6932 - accuracy: 0.5076 - val_loss: 0.6940 - val_accuracy: 0.5036
Epoch 3/5
782/782 [==============================] - 31s 40ms/step - loss: 0.6932 - accuracy: 0.5082 - val_loss: 0.6943 - val_accuracy: 0.5023
Epoch 4/5
782/782 [==============================] - 31s 39ms/step - loss: 0.6930 - accuracy: 0.5080 - val_loss: 0.6944 - val_accuracy: 0.5041
Epoch 5/5
782/782 [==============================] - 30s 38ms/step - loss: 0.6929 - accuracy: 0.5097 - val_loss: 0.6941 - val_accuracy: 0.5028


In [ ]:
model.predict(X_test)

782/782 [==============================] - 5s 6ms/step


array([[0.4961009],
       [0.4961009],
       [0.4961009],
       ...,
       [0.4961009],
       [0.4961009],
       [0.4961009]], dtype=float32)

In [ ]:
loss,accuracy = model.evaluate(X_test,y_test)

782/782 [==============================] - 7s 9ms/step - loss: 0.6941 - accuracy: 0.5028


In [ ]:
loss

0.6941041946411133

In [ ]:
accuracy

0.5027599930763245