# *Some* common terms to remember:
1. Corpus
2. Vocabulary
3. Document
4. Word

# Bag of words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch virat",
                         "virat watch virat",
                         "people write comment",
                          "virat write comment"],"output":[1,1,0,0]})

df

text  output
0    people watch virat       1
1     virat watch virat       1
2  people write comment       0
3   virat write comment       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [7]:
# Vocabulary

print(cv.vocabulary_)

{'people': 1, 'watch': 3, 'virat': 2, 'write': 4, 'comment': 0}


In [8]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 0, 2, 1, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 1]])

In [9]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 0 2 1 0]]
[[1 1 0 0 1]]


In [10]:
# New Word
cv.transform(['dhoni watch virat']).toarray()

array([[0, 0, 1, 1, 0]])

In [11]:
X = bow.toarray()
y = df['output']

#  N-grams

In [12]:
df = pd.DataFrame({"text":["people watch virat",
                         "virat watch virat",
                         "people write comment",
                          "virat write comment"],"output":[1,1,0,0]})

df

text  output
0    people watch virat       1
1     virat watch virat       1
2  people write comment       0
3   virat write comment       0

In [13]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [14]:
bow = cv.fit_transform(df['text'])

In [15]:
print(cv.vocabulary_)

{'people watch': 0, 'watch virat': 4, 'virat watch': 2, 'people write': 1, 'write comment': 5, 'virat write': 3}


In [16]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0 0 0 1 0]]
[[0 0 1 0 1 0]]
[[0 1 0 0 0 1]]


In [17]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [18]:
bow = cv.fit_transform(df['text'])

In [19]:
print(cv.vocabulary_)

{'people watch virat': 0, 'virat watch virat': 2, 'people write comment': 1, 'virat write comment': 3}


In [20]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0 0 0]]
[[0 0 1 0]]
[[0 1 0 0]]


# TF-IDF (Term frequency- Inverse document frequency)

In [22]:
df = pd.DataFrame({"text":["people watch virat",
                         "virat watch virat",
                         "people write comment",
                          "virat write comment"],"output":[1,1,0,0]})

df

text  output
0    people watch virat       1
1     virat watch virat       1
2  people write comment       0
3   virat write comment       0

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [24]:
arr = tfid.fit_transform(df['text']).toarray()

In [25]:
arr

array([[0.        , 0.61366674, 0.49681612, 0.61366674, 0.        ],
       [0.        , 0.        , 0.8508161 , 0.52546357, 0.        ],
       [0.57735027, 0.57735027, 0.        , 0.        , 0.57735027],
       [0.61366674, 0.        , 0.49681612, 0.        , 0.61366674]])

In [26]:
print(tfid.idf_)

[1.51082562 1.51082562 1.22314355 1.51082562 1.51082562]
